submitting login usecase
EBIBioStudies/submission-tool pull request #1
Opened 2024-01-04 12:10 UTC by behrangi

[#186332911]

2024-01-04 14:34 UTC, awaisathar requested changes
Please see the comments. One major change is about using Composition API

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/assets/main.css
> +.invalid-inp {
This is probably not needed. We should use bootstrap classes. Please see Attribute.vue for a reference

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailActivation.vue
> +  export default {
Go with Composition API here

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +<template>
We can perhaps merge this component in the main pages. Abstracting out made sense in the previous version where email was mandatory but now it's not so the flows are essentially different

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +            <input type="email" id="email" name="email" email="true" autofocus="" required="" v-model="email" placeholder="Email" @input="updateEmail" class="form-control"><!---->
The following would be more readable. This will go away anyway when merged into parent pages.

```
<div v-if="success">
   .....
</div>
<div v-else>
   ....
</div>
```

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +export default {
Please use Composition API

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +    const succeed = ref(false);
`success`

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +    const captchaPublicKey = ref(import.meta.env.VITE_CAPTCHA_PUBLIC_KEY);
This should be served from the server

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +      const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
Email is only needed for activation and not for login.

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +  props:{
This wil become `const props = defineProps(['title','message',`...`]);`

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +      default: '6Lc8JN0UAAAAAN4yxc0Ms6qIZ3fml-EYuuD_cTKi'
This should come from the server

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +<style scoped>
delete unused scoped styles

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +            <div v-if="!validateEmail" class="invalid-inp">Please enter a valid email</div>
`isValidEmail` has better semantics

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/Register.vue
> +            <div v-if="form.name && !validName" class="invalid-inp">Please enter a valid name</div>
`isValidName` has better semantics. Same for all boolean variables in v-if

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/Register.vue
> +    const handleSubmit = async () => {
Let's not use the verb `handle` in any method

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/Register.vue
> +          console.log(response);
Please remove all `console.log`s

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/services/AuthService.js
> +const generalPost = (url='', data) => {
Let's use `axios` everywhere instead of wrapping it in another method. This will become two methods for registration and activation

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +        const response = await AuthService.generalPost(props.url, parameters);
Let's use `axios` everytwhere instead of wrapping it in another method

2024-01-04 14:34 UTC, awaisathar commented on frontend/src/pages/login/Register.vue
> +          const response = await AuthService.generalPost('/api/auth/register', form.value);
Let's use `axios` everytwhere instead of wrapping it in another method.

2024-01-09 11:01 UTC, behrangi commented on frontend/src/pages/login/EmailComponent.vue
> +<template>
I do not get what do you mean from "merge this component in the main pages".
It is using in 2 different usecase (reactivation and forgotton password) and have similar functionality in the both usecases

2024-01-09 11:01 UTC, behrangi commented on frontend/.env
> +VITE_INSTANCE_KEY=9c584ae3-678a-4462-b685-54c37a1bc047
What is the url which serve this information from server side?

2024-01-09 11:03 UTC, behrangi commented on frontend/src/pages/login/EmailComponent.vue
> +    const captchaPublicKey = ref(import.meta.env.VITE_CAPTCHA_PUBLIC_KEY);
Which url is serving this? I was trying to follow old submission tool usecases.

2024-01-09 11:05 UTC, behrangi commented on frontend/src/pages/login/EmailComponent.vue
> +      const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
Yes, but I am using it just for activation and forgetting password usecase not login

2024-01-09 11:10 UTC, awaisathar commented on frontend/.env
> +VITE_INSTANCE_KEY=9c584ae3-678a-4462-b685-54c37a1bc047
none. The current submission tool exposes this information and we should avoid that.

2024-01-09 11:12 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +      const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
The file is on the path `/login` so probably should be moved

2024-01-09 11:14 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +<template>
It is similar but small enough to replicate in the main pages rather than abstracting out a new component. It will also enable us incorporating the success and failure messages in the page rather than passing it to the component and creating extra v-ifs for rendering

2024-01-09 11:15 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +    const captchaPublicKey = ref(import.meta.env.VITE_CAPTCHA_PUBLIC_KEY);
None. This needs not be public. The current version is not quite right here.

2024-01-09 11:54 UTC, behrangi commented on frontend/src/pages/login/EmailComponent.vue
> +<template>
It is encapsulating: captcha, validation, submitting and error handling in two usecases and made these 2 usecases so mall. So if I understand properly you mean copy its code in each use case?

2024-01-09 12:41 UTC, awaisathar commented on frontend/src/pages/login/EmailComponent.vue
> +<template>
Yes, the necessary abstraction is already in vue-recaptcha. Validation is one line of code `isValidEmail.value = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email?.value || '')` and error handling is component specific. This way we will also get rid of the `@email-updated` message which is used only once.

2024-01-10 17:32 UTC, awaisathar requested changes
Fixed errors due to a spring issue. Please fix the UI issues as discussed

2024-01-26 10:31 UTC, awaisathar approved these changes
LGTM

2024-01-26 10:31 UTC, merged